# Generated by Django 6.0.4 on 2026-04-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('desc', models.TextField(verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'варенье',
                'verbose_name_plural': 'Варенья',
            },
        ),
        migrations.CreateModel(
            name='ImgJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='jam/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False)),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.jam', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
